version: "3"

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    container_name: postgresql-boilerplate
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=api-boilerplate
